app:
  build: .
  volumes:
    - ./:/srv/src/timeside-dummy/
  command: "true"

notebook:
  build: .
  volumes:
    - ./:/srv/src/timeside-dummy/
  ports:
    - "8888:8888"
  command: sh -c "jupyter notebook --allow-root --no-browser --ip=0.0.0.0"
